import type { Metadata } from 'next'
import { THEME_FONTS } from './_constants/theme'
import './globals.css'

export const metadata: Metadata = {
  title: 'Pomodoro app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="red-variant">
      <body className={Object.values(THEME_FONTS).join(' ')}>{children}</body>
    </html>
  )
}
