import type { Metadata } from 'next'
import { setAppFont, THEME_FONTS } from './_constants/theme'
import './globals.css'
import { ThemeProvider } from 'next-themes'
import { FontProvider } from '@/_providers/font-provider'

export const metadata: Metadata = {
  title: 'Pomodoro app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  if (typeof window !== 'undefined') {
    const storedAppSetings = localStorage.getItem('pomodoro-app@appSetings')

    if (storedAppSetings) {
      const parsedAppSetings = JSON.parse(storedAppSetings)
      setAppFont(parsedAppSetings.theme.font)
    }
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <FontProvider />

      <body className={Object.values(THEME_FONTS).join(' ')}>
        <ThemeProvider storageKey="pomodoro-app@theme">
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
